### PR TITLE
Fix `intranode_allgather` benchmarks

### LINKED ISSUE #23: Explanations of `all_gather` benchmarks
`intranode_all_gather` of NCCL is much more performant than our own `intranode_all_gather`. It confuses me that our mesh `intranode_all_gather` only yields bus bandwidth of 93GBps, which is way lower than H20/H100 NVLink unidirectional bandwidth of 450GBps. I suppose it is because mesh algorithm in a switch topology will lead to network congestion considering that the bandwidth is shared by all destination ranks. What is your opinion? From my perspective, using ring algorithm is necessary in this circumstance.

In addition, is there any way to utilize NVLS using CUDA host API? This is worth noting because NVLink SHARP can yield better performance for `all_reduce`.

Furthermore, I found that the benchmarks for `all_gather` has the following problems:
- the bus bandwidths of NCCL is lower than `nccl_tests`,
- the bus bandwidth of NCCL starts to decrease when data size is greater than 256MB, which is inconsistent with `nccl_tests` showing higher bandwidths for larger data size.

I suspect the reason is the measurement of NCCL in our benchmark implicitly includes irrelevant operations, for example, tensor memory allocation perhaps, which is consistent with the phenomenon that bandwidths decrease after 256MB considering the fact that memory allocation becomes dominant compared to communications.

By the way, it would be better if you provide the versions of NCCL, NVSHMEM and CUDA used in the benchmarks.

The following is the benchmarks I ran on H20 machine:
```
===============================================================================================
 All-Gather Benchmark (world_size=8, dtype=torch.bfloat16)
 Warmup Iterations: 10, Benchmark Iterations: 50
===============================================================================================
   Size (KB) |     NCCL Time (ms) |  NVSHMEM Time (ms) |     NCCL BW (GB/s) |  NVSHMEM BW (GB/s)
------------------------------------------------------------------------------------------------
           4 |             0.1220 |             0.0551 |               0.24 |               0.52
          16 |             0.1217 |             0.0566 |               0.94 |               2.03
          64 |             0.1230 |             0.0572 |               3.73 |               8.02
         256 |             0.1366 |             0.0662 |              13.43 |              27.73
        1024 |             0.1246 |             0.1016 |              58.93 |              72.24
        2048 |             0.1258 |             0.1759 |             116.65 |              83.44
        4096 |             0.1990 |             0.3084 |             147.54 |              95.19
        8192 |             0.2899 |             0.5916 |             202.53 |              99.26
       16384 |             0.5197 |             1.2200 |             225.99 |              96.27
       32768 |             0.9646 |             2.5366 |             243.51 |              92.60
       65536 |             1.8918 |             5.0699 |             248.32 |              92.66
      131072 |             3.5623 |            10.1781 |             263.74 |              92.31
      262144 |            13.0524 |            20.2917 |             143.96 |              92.60
      524288 |            69.9399 |            40.5695 |              53.73 |              92.63
     1048576 |           127.8313 |            81.0104 |              58.80 |              92.78
```

The following are the benchmarks from `nccl_tests`:
```
#
#                                                              out-of-place                       in-place          
#       size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong
#        (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
    16777216        524288     float    none      -1    68.16  246.13  215.37      0    66.67  251.63  220.18      0
    33554432       1048576     float    none      -1    125.6  267.22  233.81      0    119.8  280.19  245.17      0
    67108864       2097152     float    none      -1    209.0  321.14  281.00      0    205.8  326.16  285.39      0
   134217728       4194304     float    none      -1    390.5  343.70  300.74      0    384.9  348.74  305.15      0
   268435456       8388608     float    none      -1    725.2  370.18  323.91      0    719.6  373.03  326.40      0
   536870912      16777216     float    none      -1   1388.3  386.71  338.37      0   1383.5  388.05  339.55      0
  1073741824      33554432     float    none      -1   2723.0  394.33  345.04      0   2697.2  398.09  348.33      0
  2147483648      67108864     float    none      -1   5360.1  400.64  350.56      0   5299.2  405.24  354.59      0
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 300.847
```

### PR DESCRIPTION
**Pull request by Gin-Sin**
Fixes #23 

As mentioned in issue #23, the bus bandwidth drops when data size(per rank) is greater than 256MB, which is abnormal since `nccl_tests` has shown that larger data size is expected to yield better performance. After studying and experimenting, disabling torch watchdog by setting `TORCH_NCCL_BLOCKING_WAIT=1` works well on my H20 machine. Simply put, torch watchdog is a thread to handle NCCL errors and will preempt the thread which is about to launch NCCL operators. So torch watchdog leads to a launch skew among all the ranks by postponing the kernel launch of one or several of all ranks.

However, I still cannot explain why are there so many `cudaFree` postponing kernel launch shown by `Nsight System`. The mechanism under the hood is still a maze to me. To continue features development, I suppose it is appropriate to temporarily fix this bug in benchmark, and perhaps later I or anyone else provide a document to illustrate this bug.

### CODE REVIEW

File: scripts/run_bench_intranode_allgather.sh [hunk 1]
```diff
@@ -8,6 +8,9 @@ fi
 
 NPROC_PER_NODE=$1
 
+# export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True"
```
Comment (KuangjuX) [inline scripts/run_bench_intranode_allgather.sh:11]: Almost LGTM! I'd like to ask if `PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True"` is effective in the current benchmark? Can you add a comment or delete it if it doesn't work?

**Review by KuangjuX — APPROVED** [review]
LGTM
